### ISSUE TITLE
[Summarize] Comparison method violates its general contract!

### ISSUE THREAD

**Issue by ArnaudParant** [mohaps/xtractor#3]
Hello,

I had a little issue with summarize when I launched the project on my machine.

`WARNING: Failed to summarize extracted text. error = Comparison method violates its general contract!`

It is a error in the tldr project, utils/Words.java at line 157:

```
if (s1.charAt(i) > s2.charAt(i)) {
    return -1;
} else if (s1.charAt(i) > s2.charAt(i)) {
   return 1;
}
```

The else if condition should be `s1.charAt(i) < s2.charAt(i)` to work, if I well understand the algorithm.

Kind regards,
Arnaud

**Comment by mohaps** [comment]
Fixed https://github.com/mohaps/xtractor/commit/12fc39490eb1c88a2ed77aaf3a6852864f56b2c0

Thanks. Was a typo
